seo: 
  site_name: 
  title: 
  description:  
  social_image: 
  social-image-alt: 
  twitter_card: 
  twitter_description:  
  author: 
  favicon_image: 
_comments:
 title: 
 social_image: 

social: 
  instagram_username:
  facebook_url:
  twitter_username: 
  
footer:
  footer-logo-text: true
  font_color: light-text
  footer-logo: Maud & Ivy
  footer-logo_image: 
  footer-logo-alt:

design: 
  dark-text_color: '#453540'
  bg-color_color: '#f7efed'
  light-text_color: '#fdefe6'
  text-gold_color: '#A5946E'
  text-hover_color: '#a84f61'
  light-text-hover_color: '#f0dcb2'
  banner-color_color: '#ffe5df'
  banner-color1_color: '#DFD1B9'
  banner-color-opacity_color: '#ffc79eA6'
  footer-color_color: '#c28789'